spring:
     application:
          name:

     datasource:
          url: jdbc:mysql://localhost:3306/cinebee
          username: ${DB_USERNAME}
          password: ${DB_PASSWORD}
          driver-class-name: com.mysql.cj.jdbc.Driver

     data:
          redis:
               host: localhost
               port: 6379
               password: ${REDIS_PASSWORD:}
               ssl:
                    enabled: false

     jackson:
          date-format: dd/MM/yyyy
          time-zone: Asia/Ho_Chi_Minh

     mail:
          host: smtp.gmail.com
          port: 587
          username: ${MAIL_USERNAME}
          password: ${MAIL_PASSWORD}
          properties:
               mail:
                    smtp:
                         auth: true
                         starttls:
                              enable: true

     jpa:
          hibernate:
               ddl-auto: update

     config:
          import: "optional:classpath:.env"

server:
     port: 8080

jwt:
     secret: aVeryLongRandomSecretKeyOfAtLeast32Chars!
     expirationMs: 3600000
     header: Authorization
     prefix: Bearer

recaptcha:
     secret: ${RECAPTCHA_SECRET}

google:
     client-id: ${GOOGLE_CLIENT_ID}
     client-secret: ${GOOGLE_CLIENT_SECRET}

cloudinary:
     cloud_name: ${CLOUDINARY_CLOUD_NAME}
     api_key: ${CLOUDINARY_API_KEY}
     api_secret: ${CLOUDINARY_API_SECRET}

momo:
     partnerCode: ${MOMO_PARTNER_CODE}
     accessKey: ${MOMO_ACCESS_KEY}
     secretKey: ${MOMO_SECRET_KEY}
     endpoint: https://test-payment.momo.vn/gw_payment/transactionProcessor
     redirectUrl: http://localhost:8080/api/v1/payments/momo/return
     ipnUrl: http://localhost:8080/api/v1/payments/momo/ipn
