spring:
  application:
    name: cinebee

  datasource:
    url: jdbc:mysql://localhost:3306/cinebee
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: false

  jackson:
    date-format: dd/MM/yyyy
    time-zone: Asia/Ho_Chi_Minh

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: "optional:classpath:.env"

server:
  port: 8080

jwt:
  secret: aVeryLongRandomSecretKeyOfAtLeast32Chars!
  expiration: 3600
  header: Authorization
  prefix: Bearer

recaptcha:
  secret: ${RECAPTCHA_SECRET}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
